name: GameSyncBot
nicknames:
    gamesync01: JackSparrow
    gamesync2: AshKetchum
    gamesync03: MonkeyDLuffy
    gamesync4: Enzio
    gamesync6: Naruto
    gamesync8: SolidSnake
    gamesync10: Mario
    gamesync12: SpiderMan
    gamesync14: Luigi
    gamesync16: Batman
    gamesync18: IronMan
    gamesync20: Link
    gamesyncgaming: MasterChief
    ericsdpchelp: CaptainAmerica